# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - nix build .#portfolio

  build:
    cmds:
      - ./node_modules/.bin/webpack
    env:
      WEBPACK_ENV: prod

  deps:
    cmds:
      - yarn
      - elm2nix convert > elm-srcs.nix
      - elm2nix snapshot > registry.dat

  clean:
    cmds:
      - cmd: rm -rf ./dist
        ignore_error: true
    silent: true

  format:
    cmds:
      - elm-format src/ --yes

  test:
    cmds:
      - elm-test

  run:
    cmds:
      - ./node_modules/.bin/webpack-dev-server
